package sportmanagementsystemhibernate;
// Generated Jul 21, 2020 12:10:09 PM by Hibernate Tools 4.3.1



/**
 * Foosball generated by hbm2java
 */
public class Foosball  implements java.io.Serializable {


     private int playerId;
     private String name;
     private Integer age;
     private Integer matches;
     private String location;

    public Foosball() {
    }

	
    public Foosball(int playerId) {
        this.playerId = playerId;
    }
    public Foosball(int playerId, String name, Integer age, Integer matches, String location) {
       this.playerId = playerId;
       this.name = name;
       this.age = age;
       this.matches = matches;
       this.location = location;
    }
   
    public int getPlayerId() {
        return this.playerId;
    }
    
    public void setPlayerId(int playerId) {
        this.playerId = playerId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Integer getAge() {
        return this.age;
    }
    
    public void setAge(Integer age) {
        this.age = age;
    }
    public Integer getMatches() {
        return this.matches;
    }
    
    public void setMatches(Integer matches) {
        this.matches = matches;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }




}


