package sportmanagementsystemhibernate;
// Generated Jul 21, 2020 12:10:09 PM by Hibernate Tools 4.3.1



/**
 * SportsManagement generated by hbm2java
 */
public class SportsManagement  implements java.io.Serializable {


     private int employeeId;

    public SportsManagement() {
    }

    public SportsManagement(int employeeId) {
       this.employeeId = employeeId;
    }
   
    public int getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(int employeeId) {
        this.employeeId = employeeId;
    }




}


